version: "3.8"

services:

  eurco:
    image: amiraqaie1376/openvins:latest
    container_name: eurco
    command: bash -c "source /opt/ros/humble/setup.bash && source /root/ros2_ws/install/setup.bash && ros2 bag play /root/dataset/V1_01_easy.db3"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/Git/Dataset/V1_01_easy/:/root/dataset
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    stdin_open: true
    tty: true
    ipc: host
    pid: host