%YAML:1.0

cam0:
  # T_imu_cam:
  #     - [0.0, 0.0, 1.0, 0.0]
  #     - [-1.0, 0.0, 0.0, -0.05]
  #     - [0.0, -1.0, 0.0, 0.0]
  #     - [0.0, 0.0, 0.0, 1.0] 
  T_imu_cam:
      - [0.0, -1.0, 0.0, 0.05]
      - [0.0, 0.0, -1.0, 0.0]
      - [1.0, 0.0, 0.0, 0.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [457.84999843514953, 457.84999843514953, 320.5, 240.5] #fu, fv, cu, cv
  resolution: [640, 480]
  rostopic: /stereo/right/image_raw
cam1:
  # T_imu_cam:
  #     - [0.0, 0.0, 1.0, 0.0]
  #     - [-1.0, 0.0, 0.0, 0.05]
  #     - [0.0, -1.0, 0.0, 0.0]
  #     - [0.0, 0.0, 0.0, 1.0] 
  T_imu_cam:
    - [0.0, -1.0, 0.0, 0.05]
    - [0.0, 0.0, -1.0, 0.0]
    - [1.0, 0.0, 0.0, 0.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [457.84999843514953, 457.84999843514953, 320.5, 240.5] #fu, fv, cu, cv
  resolution: [640, 480]
  rostopic: /stereo/left/image_raw